import Head from "next/head";
import Link from "next/link";
import { db } from "@/server/firebase";
import {
  collection,
  getDocs,
  onSnapshot,
  doc,
  deleteDoc,
} from "firebase/firestore";
import { useEffect, useState } from "react";

export default function Home() {
  const [product, setProduct] = useState([]);
  const [checkedIds, setCheckedIds] = useState([]);
  const colRef = collection(db, "products");

  // Get data
  const getData = () => {
    const unsubscribe = onSnapshot(colRef, (snapshot) => {
      setProduct(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getData();
  }, []);

  const handleCheckboxChange = (id) => {
    setCheckedIds(
      checkedIds.includes(id)
        ? checkedIds.filter((i) => i !== id)
        : [...checkedIds, id]
    );
  };

  const handleDelete = async (e) => {
    e.preventDefault();
    for (const id of checkedIds) {
      const docRef = doc(db, "products", id);
      await deleteDoc(docRef);
    }
    setCheckedIds([]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my-10">
        <div className="max-w-2xl mx-auto">
          <header>
            <nav className="flex items-center border-b-4 border--[#424242] pb-4">
              <h1 className="text-2xl font-bold text-[#424242]">
                Product List
              </h1>
              <div className="ml-auto space-x-4">
                <Link href="/add">
                  <button className="px-4 py-2 bg-green-500 rounded-lg font-semibold text-white">
                    ADD
                  </button>
                </Link>
                <button
                  type="submit"
                  onClick={handleDelete}
                  id="delete-product-btn"
                  className="px-4 py-2 bg-red-500 rounded-lg font-semibold text-white"
                >
                  MASS DELETE
                </button>
              </div>
            </nav>
          </header>
          {product && <div className="grid grid-cols-3 mt-10 gap-4">
            {product.map((product) => {
              const productType = product.productType;
              const details =
                productType === "furniture"
                  ? `Dimension: ${product.height}x${product.width}x${product.length}`
                  : productType === "book"
                  ? `Weight: ${product.weight}KG`
                  : `Size: ${product.size} MB`;

              return (
                <div
                  className="flex justify-center p-5 shadow-md shadow-[#424242]"
                  key={product.id}
                >
                  <div>
                    <input
                      type="checkbox"
                      className="delete-checkbox"
                      onChange={() => handleCheckboxChange(product.id)}
                    />
                  </div>
                  <div className="flex items-center flex-col text-center font-semibold">
                    <span>{product.sku}</span>
                    <span>{product.name}</span>
                    <span>{product.price} $</span>
                    <span>{details}</span>
                  </div>
                </div>
              );
            })}
          </div>}
        </div>
      </main>
    </>
  );
}
